"""initial schema

Revision ID: 1b4cb43f5813
Revises: 
Create Date: 2026-09-30 19:20:20.273650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4cb43f5813'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_deliveries',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_attempt_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retryable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'channel', name='idx_alert_deliveries_alert_channel')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('alert_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digest_deliveries',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('digest_type', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest_type', 'period_start', 'period_end', 'channel', name='idx_digest_deliveries_identity')
    )
    op.create_table('explanations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('explanation_type', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('llm_provider', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('llm_error', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_type', 'subject_id', name='idx_explanations_subject')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_events',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('event_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timeframe', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_records',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('strategy_version', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_alerts',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('alert_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), server_default='XAUUSD', nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('dedup_key', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_table('monitoring_baseline',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('saved_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='monitoring_baseline_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_test_sends',
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('last_success_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('trade_reviews',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('llm_error', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('trade_date', sa.Text(), nullable=False),
    sa.Column('trade_time', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('session', sa.Text(), nullable=True),
    sa.Column('entry', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('planned_rr', sa.Float(), nullable=True),
    sa.Column('setup', sa.Text(), nullable=True),
    sa.Column('market_regime', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.Text(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('rule_followed', sa.Text(), nullable=True),
    sa.Column('mistake', sa.Text(), nullable=True),
    sa.Column('exit_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='OPEN', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fundednext_context',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('data_available', sa.Boolean(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=True),
    sa.Column('phase', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('today_pnl', sa.Float(), nullable=True),
    sa.Column('daily_loss_remaining', sa.Float(), nullable=True),
    sa.Column('daily_loss_used_pct', sa.Float(), nullable=True),
    sa.Column('max_drawdown_remaining', sa.Float(), nullable=True),
    sa.Column('max_drawdown_used_pct', sa.Float(), nullable=True),
    sa.Column('daily_loss_pct_rule', sa.Float(), nullable=True),
    sa.Column('max_loss_pct_rule', sa.Float(), nullable=True),
    sa.Column('safety_level', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', name='idx_fundednext_context_trade_id')
    )
    op.create_table('journal_context',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('h4_bias', sa.Text(), nullable=True),
    sa.Column('h1_bias', sa.Text(), nullable=True),
    sa.Column('m15_bias', sa.Text(), nullable=True),
    sa.Column('m5_bias', sa.Text(), nullable=True),
    sa.Column('regime', sa.Text(), nullable=True),
    sa.Column('liquidity', sa.Text(), nullable=True),
    sa.Column('mss', sa.Text(), nullable=True),
    sa.Column('displacement', sa.Text(), nullable=True),
    sa.Column('session', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_chunks')
    op.drop_table('journal_context')
    op.drop_table('fundednext_context')
    op.drop_table('trades')
    op.drop_table('trade_reviews')
    op.drop_table('notification_test_sends')
    op.drop_table('monitoring_baseline')
    op.drop_table('monitoring_alerts')
    op.drop_table('memory_records')
    op.drop_table('market_events')
    op.drop_table('knowledge_documents')
    op.drop_table('explanations')
    op.drop_table('digest_deliveries')
    op.drop_table('alerts')
    op.drop_table('alert_deliveries')
    op.drop_table('ai_messages')
    # ### end Alembic commands ###
