"""add entry_model_judgments table

Revision ID: 680f32d0b8c6
Revises: 1b4cb43f5813
Create Date: 2026-10-09 12:31:14.981351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680f32d0b8c6'
down_revision: Union[str, None] = '1b4cb43f5813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_model_judgments',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('candidate_key', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('snapshot_fingerprint', sa.Text(), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('candidate_created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('evaluated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('llm_provider', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_category', sa.Text(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('quality', sa.Text(), nullable=True),
    sa.Column('verdict_payload', sa.Text(), nullable=True),
    sa.Column('is_reassessment', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entry_model_judgments_candidate_key', 'entry_model_judgments', ['candidate_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_entry_model_judgments_candidate_key', table_name='entry_model_judgments')
    op.drop_table('entry_model_judgments')
    # ### end Alembic commands ###
